# Config template

# Configuration variables for authentication.
[auth]
# The file that contains the secret key for hashing passwords. Please keep this key safe!
#
# NOTE: Any modifications to the secret key will invalidate all passwords hashed with the previous key,
# meaning that all passwords will fail validation. On such an event, you may have to reset or clear all passwords.
#
# To generate a secret key, you can run the following command:
# openssl rand -base64 4096 > secret.key
secret_key_path = "secret.key"


# Configuration variables for Redis
[redis]
url = "redis://localhost" # The redis connection url

# Configuration variables for the server itself.
[server]
port = 8081 # The port on which the server will listen, defaults to 8081.

# Configuration variables for the database.
[database]
host = "localhost" # Defaults to localhost
port = 5432 # Defaults to 5432
username = "postgres" # Defaults to postgres
password = "..." # Database password, remove this if your database does not have one
database = "turbine" # Defaults to turbine

# Configuration variables for GitHub oauth details
[github]
client_id = "..." # Your client id
client_secret = "..." # Your client secret
