# Config template

# Configuration variables for authentication.
[auth]
# The file that contains the secret key for hashing password.
# NOTE: If the secret key changed, all the password that was hashed with another key can no longer be verified.
# Please keep this key safe.
# To generate a secret key, you can use the command openssl rand -base64 4096 > secret.key
secret_key_path = "secret.key"


# Configuration variables for Redis
[redis]
url = "redis://localhost" # The redis connection url

# Configuration variables for the server itself.
[server]
port = 8081 # The port on which the server will listen, defaults to 8081.

# Configuration variables for the database.
[database]
host = "localhost" # Defaults to localhost
port = 5432 # Defaults to 5432
username = "postgres" # Defaults to postgres
password = "..." # Database password, remove this if your database does not have one
database = "turbine" # Defaults to turbine

# Configuration variables for GitHub oauth details
[github]
client_id = "..." # Your client id
client_secret = "..." # Your client secret
